name: meta_critic

channels:
  - defaults
  - conda-forge

dependencies:
  - python => 3.10
  - pip
  - pip:
      - torchviz
  - cmake >= 3.11
  - make
  - cxx-compiler
  - gxx = 10
  - numpy
  - matplotlib
  - pyyaml
  - tqdm
  - wandb